FROM node:18-alpine

RUN npm install -g ts-node

WORKDIR /usr/src/app

ARG BASE_URL
ARG SUPABASE_URL
ARG SUPABASE_PUBLIC_ANON_KEY
ARG SUPABASE_KEY_SERVICE_ROLE
ARG EMAIL
ARG EMAIL_PASSWORD
ARG JWT_PUBLIC_KEY
ARG DISCORD_GUILD_ID
ARG DISCORD_TOKEN
ARG DISCORD_CLIENT_ID
ARG BOT_TOKEN
ARG TRYOUT_ROLE_ID
ARG ACADEMY_ROLE_ID
ARG FIRST_TEAM_ROLE_ID
ARG LEGEND_ROLE_ID
ARG TRYOUT_CHANNEL
ARG ACADEMY_CHANNEL
ARG FIRST_TEAM_CHANNEL
ARG LEGEND_CHANNEL
ARG TRYOUT_GA
ARG ACADEMY_GA
ARG FIRST_TEAM_GA
ARG LEGEND_GA

COPY package*.json ./

COPY . .

RUN npm install


ENV PORT=8000

ENV BASE_URL=$BASE_URL
ENV SUPABASE_URL=$BASE_URL
ENV SUPABASE_PUBLIC_ANON_KEY=$SUPABASE_PUBLIC_ANON_KEY
ENV SUPABASE_KEY_SERVICE_ROLE=$SUPABASE_KEY_SERVICE_ROLE
ENV EMAIL=$EMAIL
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD
ENV JWT_PUBLIC_KEY=$JWT_PUBLIC_KEY
ENV DISCORD_GUILD_ID=$DISCORD_GUILD_ID
ENV DISCORD_TOKEN=$DISCORD_TOKEN
ENV DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
ENV BOT_TOKEN=$BOT_TOKEN
ENV TRYOUT_ROLE_ID=$TRYOUT_ROLE_ID
ENV ACADEMY_ROLE_ID=$ACADEMY_ROLE_ID
ENV FIRST_TEAM_ROLE_ID=$FIRST_TEAM_ROLE_ID
ENV LEGEND_ROLE_ID=$LEGEND_ROLE_ID
ENV TRYOUT_CHANNEL=$TRYOUT_CHANNEL
ENV ACADEMY_CHANNEL=$ACADEMY_CHANNEL
ENV FIRST_TEAM_CHANNEL=$FIRST_TEAM_CHANNEL
ENV LEGEND_CHANNEL=$LEGEND_CHANNEL
ENV TRYOUT_GA=$TRYOUT_GA
ENV ACADEMY_GA=$ACADEMY_GA
ENV FIRST_TEAM_GA=$FIRST_TEAM_GA
ENV LEGEND_GA=$LEGEND_GA


EXPOSE 8000

CMD ["npm", "run","start:deploy"]